additional_parameters = "--metadata_reso \"1024,1024\""
async_upload = false
auto_generate_black_control_images = false
base_weights_multiplier = 1
blocks_to_swap = 58
caching_latent_batch_size = 1
caching_latent_console_back = ""
caching_latent_console_num_images = 0
caching_latent_console_width = 80
caching_latent_debug_mode = ""
caching_latent_device = "cuda"
caching_latent_keep_cache = true
caching_latent_num_workers = 4
caching_latent_skip_existing = true
caching_teo_batch_size = 4
caching_teo_device = "cpu"
caching_teo_fp8_vl = false
caching_teo_keep_cache = true
caching_teo_num_workers = 4
caching_teo_skip_existing = true
caption_strategy = "folder_name"
compile = true
compile_backend = "inductor"
compile_cache_size_limit = 0
compile_dynamic = "auto"
compile_fullgraph = false
compile_mode = "default"
convert_to_diffusers = false
convert_to_safetensors = false
create_missing_captions = true
custom_network_module = ""
dataset_batch_size = 1
dataset_bucket_no_upscale = false
dataset_cache_directory = "cache_dir"
dataset_caption_extension = ".txt"
dataset_config = "/home/Ubuntu/apps/StableSwarmUI/Models/diffusion_models/dataset_config_20251020_213007.toml"
dataset_config_mode = "Generate from Folder Structure"
dataset_control_directory = "edit_images"
dataset_enable_bucket = false
dataset_qwen_image_edit_control_resolution_height = 0
dataset_qwen_image_edit_control_resolution_width = 0
dataset_qwen_image_edit_no_resize_control = false
dataset_resolution_height = 1024
dataset_resolution_width = 1024
ddp_gradient_as_bucket_view = false
ddp_static_graph = false
ddp_timeout = 0
debug_mode = "None"
diffusers_output_dir = ""
dim_from_weights = false
disable_prompt_enhancement = true
discrete_flow_shift = 2.2
dit = "/home/Ubuntu/Downloads/SECourses_Musubi_Trainer_v23/Training_Models_Qwen/qwen_image_bf16.safetensors"
dit_dtype = "bfloat16"
dit_in_channels = 16
dynamo_backend = "no"
dynamo_mode = ""
dynamo_use_dynamic = false
dynamo_use_fullgraph = false
edit = false
edit_plus = false
extra_accelerate_launch_args = ""
faster_model_loading = false
flash3 = false
flash_attn = false
flow_shift = 7
fp8_base = false
fp8_scaled = false
fp8_vl = false
full_bf16 = true
full_fp16 = false
fused_backward_pass = true
generated_toml_path = "/home/Ubuntu/apps/StableSwarmUI/Models/diffusion_models/dataset_config_20251020_213007.toml"
gpu_ids = "0"
gradient_accumulation_steps = 1
gradient_checkpointing = true
gradient_checkpointing_cpu_offload = true
guidance_scale = 4
img_in_txt_in_offloading = false
learning_rate = 4.5e-5
log_config = false
log_prefix = ""
log_tracker_name = ""
log_with = ""
logging_dir = ""
logit_mean = 0
logit_std = 1
lr_decay_steps = 0
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_min_lr_ratio = 0
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_scheduler_timescale = 0
lr_scheduler_type = ""
lr_warmup_steps = 0
main_process_port = 0
max_data_loader_n_workers = 2
max_grad_norm = 0
max_timestep = 1000
max_train_epochs = 50
max_train_steps = 90000
mem_eff_save = true
metadata_author = ""
metadata_description = ""
metadata_license = ""
metadata_tags = ""
mixed_precision = "bf16"
mode_scale = 1
multi_gpu = false
network_module = ""
no_metadata = false
num_cpu_threads_per_process = 2
num_machines = 1
num_processes = 1
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "AdaFactor"
output_dir = "/home/Ubuntu/apps/StableSwarmUI/Models/diffusion_models"
output_name = "My_Qwen_Fine_Tuned_Model"
parent_folder_path = "/home/Ubuntu/Downloads/28_imgs_1024"
persistent_data_loader_workers = true
preserve_distribution_shape = false
safetensors_output_dir = ""
sage_attn = false
sample_at_first = false
sample_cfg_scale = 4
sample_discrete_flow_shift = 2.2
sample_guidance_scale = 1
sample_height = 1024
sample_negative_prompt = ""
sample_output_dir = ""
sample_seed = 99
sample_steps = 20
sample_width = 1024
save_every_n_epochs = 10
save_last_n_epochs = 0
save_last_n_epochs_state = 0
save_last_n_steps = 0
save_last_n_steps_state = 0
save_state = false
save_state_on_train_end = false
save_state_to_huggingface = false
scale_weight_norms = 0
sdpa = true
seed = 99
show_timesteps = ""
sigmoid_scale = 1
split_attn = true
text_encoder = "/home/Ubuntu/Downloads/SECourses_Musubi_Trainer_v23/Training_Models_Qwen/qwen_2.5_vl_7b_bf16.safetensors"
text_encoder_dtype = "bfloat16"
timestep_sampling = "sigmoid"
training_comment = ""
training_mode = "DreamBooth Fine-Tuning"
vae = "/home/Ubuntu/Downloads/SECourses_Musubi_Trainer_v23/Training_Models_Qwen/qwen_train_vae.safetensors"
vae_dtype = "bfloat16"
vae_tiling = false
wandb_run_name = ""
weighting_scheme = "mode"
xformers = false
